name: walletconnect_dart_v2_i
description: This repository contains implementation of WalletConnect v2 protocols for Dart applications, adapted from the official implementation WalletConnectFlutterV2.
version: 2.2.0
repository: https://github.com/irulast/WalletConnectDartV2_i

environment:
  sdk: '>=3.3.4 <3.4.0'

dependencies:
  web_socket_channel: ^2.4.5
  http: ^1.2.1
  cryptography: ^2.0.5
  convert: ^3.0.1
  json_annotation: ^4.7.0
  pointycastle: ^3.6.2
  x25519: ^0.1.1
  bs58: ^1.0.2
  ed25519_edwards: ^0.3.1
  event: ^2.1.2
  stream_channel: ^2.1.0
  universal_io: ^2.0.4
  stack_trace: ^1.10.0
  freezed_annotation: ^2.2.0
  web3dart: ^2.4.0
  logger: ^2.0.2+1

dev_dependencies:
  test: ^1.19.3
  build_runner: ^2.4.9
  json_serializable: ^6.5.3
  dependency_validator: ^4.0.0
  mockito: ^5.3.2
  eth_sig_util: ^0.0.9
  build_version: ^2.0.0
  freezed: ^2.2.0

